Feature/update retest
retest/recheck-logs pull request #2
Opened 2018-10-17 13:34 UTC by roesslerj

2018-10-17 13:50 UTC, enesoezel approved these changes

2018-10-29 07:57 UTC, beatngu13 requested changes

2018-10-29 07:57 UTC, beatngu13 commented on pom.xml
> +			<version>3.0.0</version>
With retest 3.0.1, we should be able to remove some exclusions.

2019-03-18 10:20 UTC, roesslerj commented
Could you re-review? Would like to show-case this today...

2019-03-18 10:23 UTC, beatngu13 approved these changes

2019-03-18 10:50 UTC, merged